### ISSUE TITLE
degreeField.valueOne

### ISSUE THREAD

**Issue by huba80** [lmueller27/Fusion360PatternsAndTextures#4]
Hi,

It might be my fault but Ive got a 3D part that I wish to apply texture to. When I try to select the mesh your add-in throws an error:

```
Failed:
Traceback (most recent call last):
  File "C:/Users/TescoJim/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/Scripts/Noise, Patterns and Textures.py", line 326, in notify
    degreeField.valueOne = calculateAppropriateNoiseLevel(body)
  File "C:\Users/TescoJim/AppData/Local/Autodesk/webdeploy/production/e3fd45ba03e541f75bf8195292579861b6ebb663/Api/Python/packages\adsk\core.py", line 36870, in _set_valueOne
    return _core.FloatSliderCommandInput__set_valueOne(self, value)
RuntimeError: 3 : invalid parameter value
```

**Comment by lmueller27** [comment]
Hey, can you please provide some screenshots of the mesh body, and the Add-In UI?

Thank you!
